import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Yields",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  // params,
}: Readonly<{
  children: React.ReactNode;
  // params: { locale: Locale };
}>) {
  // const { locale } = params;

  // // Validate locale
  // if (!routing.locales.includes(locale)) {
  //   notFound();
  // }

  // // Load translation messages for the given locale
  // const messages = await getMessages({ locale });

  return (
    <html >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <NextIntlClientProvider messages={messages} locale={locale}> */}
          {children}
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
