import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import OneSignalProvider from "@/components/OneSignalProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-poppins",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Yields",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  // params,
}: Readonly<{
  children: React.ReactNode;
  // params: { locale: Locale };
}>) {
  // const { locale } = params;

  // // Validate locale
  // if (!routing.locales.includes(locale)) {
  //   notFound();
  // }

  // // Load translation messages for the given locale
  // const messages = await getMessages({ locale });

  return (
    <html >
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Yield" />
        <link rel="manifest" href="/manifest.json"/>
        <link rel="apple-touch-icon" sizes="192x192" href="/icons/192x192.png" />
        <link rel="apple-touch-icon" sizes="512x512" href="/icons/512x512.png" />
        <link rel="apple-touch-startup-image" href="/icons/Logo=Coloured.svg" />
        <meta name="theme-color" content="000000" />

      </head>
      <body className={`${poppins.variable}  antialiased`}>
        {/* <NextIntlClientProvider messages={messages} locale={locale}> */}
          <OneSignalProvider/>
          {children}
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
